# Level 1 Module NAV
# Estimates the spacecraft states
# Inputs: All data generated by SEN Module

from .NAV_CELENAV import NAV_CELENAV
from .NAV_XNAV    import NAV_XNAV
from .NAV_CMBR    import NAV_CMBR
from .NAV_UKF     import NAV_UKF

# Module output dictionary
NAV_out = {
    "NAV_CELENAV" : None,
    "NAV_XNAV"    : None,
    "NAV_CMBR"    : None,
    "NAV_UKF"     : None
}

# Module main function
def run(NAV_in):
    NAV_CELENAV_out = NAV_CELENAV.run(NAV_in)
    NAV_XNAV_out    = NAV_XNAV.run(NAV_in)
    NAV_CMBR_out    = NAV_CMBR.run(NAV_in)
    NAV_UKF_out     = NAV_UKF.run(NAV_CELENAV_out, NAV_XNAV_out, NAV_CMBR_out)

    # Attribute outputs to NAV output
    NAV_out["NAV_CELENAV"] = NAV_CELENAV_out
    NAV_out["NAV_XNAV"]    = NAV_XNAV_out
    NAV_out["NAV_CMBR"]    = NAV_CMBR_out
    NAV_out["NAV_UKF"]     = NAV_UKF_out
    return dict(NAV_out)
