# Level 1 Module SEN
# Executes all sensor functions from the spacecraft
# Inputs: All data generated by DYN Module

from Utils.level1module import Level1Module
from .SEN_TIME.SEN_TIME import SEN_TIME
from .SEN_STR.SEN_STR   import SEN_STR
from .SEN_PSR.SEN_PSR   import SEN_PSR
from .SEN_CMB.SEN_CMB   import SEN_CMB

class SEN(Level1Module):
    def __init__(self, DYN_obj, par_override=None):

        par_override = par_override or {}

        # Instantiate modules
        self.SEN_TIME = SEN_TIME(par_override.get("SEN_TIME"))
        self.SEN_STR  = SEN_STR(par_override.get("SEN_STR"))
        self.SEN_PSR  = SEN_PSR(par_override.get("SEN_PSR"))
        self.SEN_CMB  = SEN_CMB(par_override.get("SEN_CMB"))

        # Register modules
        self.modules = [
            self.SEN_TIME,
            self.SEN_STR,
            self.SEN_PSR,
            self.SEN_CMB,
        ]

        # Initialize all modules
        for m in self.modules:
            m.state = m.initialize(DYN_obj.snapshot(), self.snapshot())

        print("SEN Module Initialized.")

    # Update time-dependent, non-integrated Level-2 modules
    def update_algebraic(self, t, DYN_obj, inputs):
        DYN_snapshot = DYN_obj.snapshot()
        for m in self.modules:
            SEN_snapshot = self.snapshot()
            m.update_algebraic(t, DYN_snapshot, SEN_snapshot, inputs)
