# Level 1 Module SEN
# Executes all sensor functions from the spacecraft
# Inputs: All data generated by DYN Module

from Utils.level1module import Level1Module
from .SEN_STR.SEN_STR   import SEN_STR

class SEN(Level1Module):
    def __init__(self, DYN_obj, par_override=None):

        par_override = par_override or {}

        # Instantiate modules
        self.SEN_STR = SEN_STR(par_override.get("SEN_STR"))

        # Register modules
        self.modules = [
        self.SEN_STR,
        ]

        # Initialize all modules
        for m in self.modules:
            m.initialize(DYN_obj.snapshot(), self.snapshot())

        print("SEN Module Initialized.")

    # Update time-dependent, non-integrated Level-2 modules
    def update_algebraic(self, t, DYN_obj, inputs):
        for m in self.modules:
            m.update_algebraic(t, DYN_obj.snapshot(), self.snapshot(), inputs)
