# Level 1 Module SEN
# Executes all sensor functions from the spacecraft
# Inputs: All data generated by DYN Module

from .SEN_STR       import SEN_STR
from .SEN_PULSAR    import SEN_PULSAR
from .SEN_BOLOMETER import SEN_BOLOMETER

# Module output dictionary
SEN_out = {
    "SEN_STR"       : None,
    "SEN_PULSAR"    : None,
    "SEN_BOLOMETER" : None,
}

# Module main function
def run(SEN_in):
    SEN_STR_out       = SEN_STR.run(SEN_in)
    SEN_PULSAR_out    = SEN_PULSAR.run(SEN_in)
    SEN_BOLOMETER_out = SEN_BOLOMETER.run(SEN_in)

    # Attribute outputs to SEN output
    SEN_out["SEN_STR"]       = SEN_STR_out
    SEN_out["SEN_PULSAR"]    = SEN_PULSAR_out
    SEN_out["SEN_BOLOMETER"] = SEN_BOLOMETER_out
    return dict(SEN_out)
