# Level 1 Module NAV
# Estimates the spacecraft states
# Inputs: All data generated by SEN Module

from Utils.level1module import Level1Module
from .NAV_EPH.NAV_EPH   import NAV_EPH
from .NAV_STR.NAV_STR   import NAV_STR
from .NAV_CEL.NAV_CEL   import NAV_CEL
from .NAV_PSR.NAV_PSR   import NAV_PSR
from .NAV_CMB.NAV_CMB   import NAV_CMB
from .NAV_EKF.NAV_EKF   import NAV_EKF
from .NAV_UKF.NAV_UKF   import NAV_UKF

class NAV(Level1Module):
    def __init__(self, SEN_obj, par_override=None):

        par_override = par_override or {}

        # Instantiate modules
        self.NAV_EPH = NAV_EPH(par_override.get("NAV_EPH"))
        self.NAV_STR = NAV_STR(par_override.get("NAV_STR"))
        self.NAV_CEL = NAV_CEL(par_override.get("NAV_CEL"))
        self.NAV_PSR = NAV_PSR(par_override.get("NAV_PSR"))
        self.NAV_CMB = NAV_CMB(par_override.get("NAV_CMB"))
        self.NAV_EKF = NAV_EKF(par_override.get("NAV_EKF"))
        self.NAV_UKF = NAV_UKF(par_override.get("NAV_UKF"))

        # Register modules
        self.modules = [
            self.NAV_EPH,
            self.NAV_STR,
            self.NAV_CEL,
            self.NAV_PSR,
            self.NAV_CMB,
            self.NAV_EKF,
            self.NAV_UKF,
        ]

        # Initialize all modules
        for m in self.modules:
            NAV_snapshot = self.snapshot()
            m.state = m.initialize(SEN_obj.snapshot(), NAV_snapshot)

        print("NAV Module Initialized.")

    # Update time-dependent, non-integrated Level-2 modules
    def update_algebraic(self, t, SEN_obj, inputs):
        # EKF
        if SEN_obj is None:
            return self.snapshot()

        SEN_snapshot = SEN_obj.snapshot()
        for m in self.modules:
            NAV_snapshot = self.snapshot()
            m.update_algebraic(t, SEN_snapshot, NAV_snapshot, inputs)
