# Level 1 Module NAV
# Estimates the spacecraft states
# Inputs: All data generated by SEN Module

from Utils.level1module import Level1Module
from .NAV_CEL.NAV_CEL   import NAV_CEL
from .NAV_PSR.NAV_PSR   import NAV_PSR

class NAV(Level1Module):
    def __init__(self, SEN_obj, par_override=None):

        par_override = par_override or {}

        # Instantiate modules
        self.NAV_CEL = NAV_CEL(par_override.get("NAV_CEL"))
        self.NAV_PSR = NAV_PSR(par_override.get("NAV_PSR"))

        # Register modules
        self.modules = [
            self.NAV_CEL,
            self.NAV_PSR,
        ]

        # Initialize all modules
        for m in self.modules:
            m.state = m.initialize(SEN_obj.snapshot())

        print("NAV Module Initialized.")

    # Update time-dependent, non-integrated Level-2 modules
    def update_algebraic(self, t, SEN_obj, inputs):
        for m in self.modules:
            m.update_algebraic(t, SEN_obj.snapshot(), inputs)
